### ISSUE TITLE
Panic/segmentation fault on GNU/Linux

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet-go#134]
**Describe the bug**
Running most commands on linux return an error.

**Environment information:**

- OS: GNU/Linux
- Platform: Linux 4.19.0-1-amd64 x86_64
- Firmware Version: Not relevant
- Go
```
GOARCH="amd64"
GOBIN=""
GOCACHE=".cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/gocode"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build083768146=/tmp/go-build -gno-record-gcc-switches"
```

**Steps to Reproduce**

1. Go to source code root dir
2. go run cmd/cli/cli.go wipe

**Actual behavior**
```
go run cmd/cli/cli.go wipe
[2019-05-29T21:37:42-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-05-29T21:37:42-04:00] ERROR [walletusb]: current configuration 1
[2019-05-29T21:37:42-04:00] INFO [skywallet]: Wipe device 26! Answer is: 0806

[2019-05-29T21:37:42-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:42-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-05-29T21:37:42-04:00] ERROR [walletusb]: current configuration 1
[2019-05-29T21:37:44-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:44-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:44-04:00] WARN [walletusb]: Warning: error at releasing interface: LIBUSB_ERROR_NOT_FOUND
[2019-05-29T21:37:44-04:00] WARN [walletusb]: Warning: error at re-attaching driver: LIBUSB_ERROR_OTHER
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ed881]

runtime stack:
runtime.throw(0x7999fe, 0x2a)
        /opt/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x6efb80, 0xc0001137d0, 0x39)
        /opt/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0001137a0 sp=0xc000113768 pc=0x40868b
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb._Cfunc_libusb_close(0x12d6760)
        _cgo_gotypes.go:618 +0x41 fp=0xc0001137d0 sp=0xc0001137a0 pc=0x679e91
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close.func1(0x12d6760)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x56 fp=0xc000113808 sp=0xc0001137d0 pc=0x680226
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close(0x12d6760)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x2b fp=0xc000113820 sp=0xc000113808 pc=0x67f20b
github.com/skycoin/hardware-wallet-go/src/skywallet/usb.(*LibUSBDevice).Close(0xc00009ce20, 0xc000113800, 0xc0001138b0, 0xc0001138e0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/skywallet/usb/libusb.go:404 +0x109 fp=0xc000113878 sp=0xc000113820 pc=0x683879
github.com/skycoin/hardware-wallet-go/src/skywallet.(*Device).Wipe(0xc000095b90, 0x2, 0xc0001801c0, 0xe, 0x40, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet.go:784 +0x2a6 fp=0xc000113928 sp=0xc000113878 pc=0x6d24c6
github.com/skycoin/hardware-wallet-go/src/cli.wipeCmd.func1(0xc0000c2580)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/cli/wipe.go:42 +0xf6 fp=0xc0001139a8 sp=0xc000113928 pc=0x6e3316
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.HandleAction(0x71d860, 0x7a0a80, 0xc0000c2580, 0xc0000ac400, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/app.go:492 +0x7c fp=0xc0001139d0 sp=0xc0001139a8 pc=0x60478c
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.Command.Run(0x78d02e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x79ea9b, 0x3f, 0x0, ...)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/command.go:210 +0x996 fp=0xc000113c30 sp=0xc0001139d0 pc=0x605986
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.(*App).Run(0xc0000d0b60, 0xc00009c020, 0x2, 0x2, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/app.go:255 +0x6af fp=0xc000113f20 sp=0xc000113c30 pc=0x602b0f
github.com/skycoin/hardware-wallet-go/src/cli.(*App).Run(...)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/cli/cli.go:124
main.main()
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/cmd/cli/cli.go:17 +0xd1 fp=0xc000113f98 sp=0xc000113f20 pc=0x6e3ee1
runtime.main()
        /opt/go/src/runtime/proc.go:200 +0x20c fp=0xc000113fe0 sp=0xc000113f98 pc=0x432a1c
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000113fe8 sp=0xc000113fe0 pc=0x45c831
exit status 2
```

**Expected behavior**
No error at all

**Additional context**
PD: some command work and other not, but the error log is always present

**Possible implementation**
no hint

**Comment by therealssj** [comment]
is this emulator or hardware wallet?

**Comment by stdevAlDen** [comment]
> is this emulator or hardware wallet?

@therealssj hardware wallet, looking at the log this looks like some thing related to libusb cgo wrapper.

**Comment by olemis** [comment]
>     * Firmware Version: Not relevant

@stdevAlDen why not relevant ?

**Comment by stdevAlDen** [comment]
> > ```
> > * Firmware Version: Not relevant
> > ```
> 
> @stdevAlDen why not relevant ?

@olemis because the problem is in the stages from hw-go -> libusb-go-wrapper --> libusb --> OS kernel, before reaching the firmware.

**Comment by therealssj** [comment]
yes, its like what @stdevAlDen said so the firmware version is not relevant
